package com.sor.restapi;

import org.restlet.resource.Directory;
import org.restlet.routing.Router;
import org.restlet.Application;
import org.restlet.Restlet;

public class UserApplication extends Application {

	@Override
    public Restlet createInboundRoot() {
        Router router = new Router(getContext());

        // Serve the files generated by the GWT compilation step.
        router.attachDefault(new Directory(getContext(), "war:///"));
        router.attach("/user", UserServerResource.class);

        return router;
    }
	
}
